# 影视仓/OK影视 订阅配置文件 (TOML格式)

spider = "https://raw.githubusercontent.com/231g-sudo/video-subscription/main/jar/custom_spider.jar;md5;41c87635d7592069884a5dafa12acabe"
wallpaper = "https://t.alcy.cc/acg"

[[sites]]
key = "豆瓣"
name = "📖 豆瓣 | 推荐/排行榜"
type = 3
api = "csp_Douban"

[[sites]]
key = "非凡资源"
name = "🔥 非凡资源 | 综合"
type = 1
api = "http://ffzy.tv/api.php/provide/vod/"

[[sites]]
key = "最大资源"
name = "📀 最大资源 | 综合"
type = 1
api = "https://www.zuidazy.com/api.php/provide/vod/"

[[sites]]
key = "金鹰资源"
name = "🦅 金鹰资源 | 综合"
type = 1
api = "https://www.jinyingzy.com/api.php/provide/vod/"

[[lives]]
name = "📡 央视/卫视"
type = 0
url = "https://live.fanmingming.cn/tv/m3u/ipv6.m3u"
playerType = 1

[[lives]]
name = "🌍 全球频道"
type = 0
url = "https://iptv-org.github.io/iptv/index.m3u"
playerType = 2

[[lives]]
name = "🔄 自动更新源"
type = 0
url = "https://raw.githubusercontent.com/Guovin/iptv-api/gd/output/result.m3u"
playerType = 1

[doh]
name = "Ali DNS"
url = "https://dns.alidns.com/dns-query"
ips = ["223.5.5.5", "223.6.6.6"]
